"""
RFP Analysis Agent — FastAPI application.

Exposes a REST API that is compatible with Microsoft Copilot Studio custom
connectors.  Import the auto-generated OpenAPI spec (GET /openapi.json) into
Copilot Studio to wire it up as a skill/action.

Endpoints
---------
POST /api/rfp/analyze   — full RFP vs response analysis (main endpoint)
GET  /health            — liveness check
GET  /openapi.json      — OpenAPI 3.1 spec (auto-generated by FastAPI)
GET  /docs              — Swagger UI
"""

from __future__ import annotations

import logging
import os
from contextlib import asynccontextmanager

import anthropic
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request, Security, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse
from fastapi.security import APIKeyHeader
from fastapi.staticfiles import StaticFiles

from src.agent import MODEL, analyze_rfp
from src.models import AnalyzeRFPRequest, AnalyzeRFPResponse, HealthResponse

load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

# ── Optional API-key auth ─────────────────────────────────────────────────────

_RFP_API_KEY = os.getenv("RFP_API_KEY", "")
_api_key_header = APIKeyHeader(name="X-API-Key", auto_error=False)


async def _verify_api_key(api_key: str | None = Security(_api_key_header)) -> None:
    """If RFP_API_KEY is set, callers must send a matching X-API-Key header."""
    if _RFP_API_KEY and api_key != _RFP_API_KEY:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing X-API-Key header.",
        )


# ── App lifecycle ─────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    if not os.getenv("ANTHROPIC_API_KEY"):
        raise RuntimeError(
            "ANTHROPIC_API_KEY environment variable is not set. "
            "Copy .env.example → .env and add your key."
        )
    logger.info("RFP Analysis Agent started (model=%s)", MODEL)
    yield
    logger.info("RFP Analysis Agent shutting down")


# ── FastAPI app ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="RFP Analysis Agent",
    description=(
        "AI-powered agent that analyses RFP responses, scores each section, "
        "identifies high-scoring areas and gaps, and recommends what needs to "
        "be done to maximise win probability. "
        "Powered by Claude Opus 4.6 (Anthropic). "
        "Compatible with Microsoft Copilot Studio custom connectors — import "
        "the OpenAPI spec from GET /openapi.json."
    ),
    version="1.0.0",
    lifespan=lifespan,
    contact={"name": "bobbynoble"},
    license_info={"name": "MIT"},
)

app.mount("/static", StaticFiles(directory="static"), name="static")

# CORS — allow Copilot Studio and other callers
_cors_origins = [o.strip() for o in os.getenv("CORS_ORIGINS", "*").split(",")]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
async def root():
    return RedirectResponse(url="/static/index.html")


@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health check",
    description="Returns the service status and the Claude model in use.",
    tags=["System"],
)
async def health() -> HealthResponse:
    return HealthResponse(status="ok", model=MODEL)


@app.post(
    "/api/rfp/analyze",
    response_model=AnalyzeRFPResponse,
    summary="Analyse an RFP response",
    description=(
        "Submit an original RFP document and a bid/response document. "
        "The agent scores each section (0–100), identifies high-performing areas, "
        "surfaces compliance gaps, and returns a prioritised list of action items "
        "and strategic recommendations. "
        "Optionally supply custom evaluation criteria with weights."
    ),
    tags=["RFP Analysis"],
    dependencies=[Security(_verify_api_key)],
    responses={
        200: {"description": "Analysis completed successfully"},
        401: {"description": "Invalid or missing X-API-Key (only when RFP_API_KEY is configured)"},
        422: {"description": "Validation error — check your request body"},
        500: {"description": "Analysis failed — see error_message for details"},
    },
)
async def analyze_rfp_endpoint(body: AnalyzeRFPRequest) -> AnalyzeRFPResponse:
    try:
        result = await analyze_rfp(body)
        return AnalyzeRFPResponse(success=True, analysis=result)
    except anthropic.AuthenticationError:
        logger.error("Anthropic authentication failed — check ANTHROPIC_API_KEY")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Anthropic API key is invalid or not configured on the server.",
        )
    except anthropic.RateLimitError:
        logger.warning("Anthropic rate limit hit")
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Rate limit reached. Please retry in a few seconds.",
        )
    except anthropic.APIStatusError as exc:
        logger.error("Anthropic API error: %s %s", exc.status_code, exc.message)
        return AnalyzeRFPResponse(
            success=False,
            error_message=f"Claude API error ({exc.status_code}): {exc.message}",
        )
    except Exception as exc:  # noqa: BLE001
        logger.exception("Unexpected error during RFP analysis")
        return AnalyzeRFPResponse(success=False, error_message=str(exc))
